"""Router agent for intent classification."""
import time
from typing import Literal
from langchain_core.messages import HumanMessage, AIMessage
from services.llm_service import get_llm_service
from services.prompt_loader import get_prompt
from graph.state import ReceptionistState
from utils.logger import log_agent_flow, log_intent_classification, log_llm_call


def _format_conversation_history(messages, max_messages=10):
    """Format conversation history for router analysis.
    
    Args:
        messages: List of messages from state
        max_messages: Maximum number of recent messages to include
    
    Returns:
        Formatted conversation history string
    """
    if not messages:
        return "No conversation history."
    
    # Get recent messages (last N messages)
    recent_messages = messages[-max_messages:] if len(messages) > max_messages else messages
    
    history_parts = []
    for msg in recent_messages:
        if isinstance(msg, HumanMessage):
            history_parts.append(f"User: {msg.content}")
        elif isinstance(msg, AIMessage):
            # Only include AI message content if it's not just tool calls
            if msg.content and msg.content.strip():
                history_parts.append(f"Assistant: {msg.content}")
        # Skip tool messages and system messages in history display
    
    if not history_parts:
        return "No conversation history."
    
    return "\n".join(history_parts)


def router_agent(state: ReceptionistState) -> ReceptionistState:
    """Router agent that classifies user intent using conversation history."""
    log_agent_flow("ROUTER", "Starting Intent Classification")
    
    messages = state.get("messages", [])
    if not messages:
        log_intent_classification("general_qa", "default (no messages)")
        return {**state, "intent": "general_qa", "conversation_context": None}
    
    # Get the last user message
    last_message = messages[-1]
    if not isinstance(last_message, HumanMessage):
        log_intent_classification("general_qa", "default (not HumanMessage)")
        return {**state, "intent": "general_qa", "conversation_context": None}
    
    # Format conversation history for context
    conversation_history = _format_conversation_history(messages)
    
    # Use conversation context from state if available (for efficiency)
    saved_context = state.get("conversation_context")
    if saved_context:
        conversation_history = f"{saved_context}\n\nRecent messages:\n{conversation_history}"
    
    # Use LLM to classify intent with full conversation context
    start_time = time.time()
    llm_service = get_llm_service()
    llm = llm_service.get_llm(temperature=0)
    
    router_prompt = get_prompt("router")
    
    # Build classification prompt with conversation history
    classification_prompt = f"""{router_prompt}

CONVERSATION HISTORY:
{conversation_history}

CURRENT USER MESSAGE:
{last_message.content}

Based on the conversation history and current message, classify the intent."""
    
    log_llm_call(llm_service.provider_name, llm_service.model_name, "Intent Classification")
    response = llm.invoke([HumanMessage(content=classification_prompt)])
    response_time = time.time() - start_time
    log_llm_call(llm_service.provider_name, llm_service.model_name, "Intent Classification", response_time)
    
    intent = response.content.strip().lower()
    
    # Validate intent
    valid_intents = ["product_inquiry", "ordering", "payment", "cancellation", "general_qa"]
    if intent not in valid_intents:
        log_intent_classification("general_qa", f"default (invalid: {intent})")
        intent = "general_qa"  # Default to general_qa if unclear
    else:
        log_intent_classification(intent, "valid")
    
    # Update conversation context for efficient memory (store summary of key points)
    # For now, we'll store a condensed version of recent history
    # In the future, this could be a summarized version generated by LLM
    updated_context = conversation_history[-500:] if len(conversation_history) > 500 else conversation_history
    
    log_agent_flow("ROUTER", "Intent Classification Complete", {
        "intent": intent,
        "history_length": len(messages),
        "context_used": True
    })
    
    return {
        **state,
        "intent": intent,
        "conversation_context": updated_context
    }


def route_to_agent(state: ReceptionistState) -> Literal["qa_agent", "ordering_agent", "payment_agent", "cancellation_agent"]:
    """Route to appropriate agent based on intent."""
    intent = state.get("intent", "general_qa")
    
    if intent == "product_inquiry" or intent == "general_qa":
        log_agent_flow("ROUTER", "Routing to QA Agent")
        return "qa_agent"
    elif intent == "ordering":
        log_agent_flow("ROUTER", "Routing to Ordering Agent")
        return "ordering_agent"
    elif intent == "payment":
        log_agent_flow("ROUTER", "Routing to Payment Agent")
        return "payment_agent"
    elif intent == "cancellation":
        log_agent_flow("ROUTER", "Routing to Cancellation Agent")
        return "cancellation_agent"
    else:
        log_agent_flow("ROUTER", "Routing to QA Agent (default)")
        return "qa_agent"
